using Pf2e.Client.State;

namespace Pf2e.Client.Catalog;

/// <summary>Our own words, never Paizo's: the ingest withholds rule prose, and these fill the gap
/// with a plain explanation a new player can act on.</summary>
public sealed record CategoryNote(string Section, string Blurb);

public static class GroupNotes
{
    public static IReadOnlyDictionary<GroupKey, string> All { get; } = new Dictionary<GroupKey, string>
    {
        [GroupKey.Build] = "The choices that make a character: who they are, where they come from, and what they trained as.",
        [GroupKey.Feats] = "The special abilities you pick as you level up, including archetypes that borrow from outside your class.",
        [GroupKey.Spells] = "Every spell and ritual, and the four traditions of magic that decide which ones a caster can learn.",
        [GroupKey.Gear] = "Everything you can carry, wear or wield, from rope and rations to magic weapons, relics and the curses they hide.",
        [GroupKey.Play] = "What you actually do at the table: the actions you take, the conditions that hit you, and the skills you roll.",
        [GroupKey.Reference] = "The lookup shelf: traits, languages, gods, companions and the other terms the rest of the rules point to.",
    };

    public static string Of(GroupKey group) => All.GetValueOrDefault(group, string.Empty);
}

public static class CategoryNotes
{
    public static IReadOnlyDictionary<string, CategoryNote> All { get; } =
        new Dictionary<string, CategoryNote>(StringComparer.Ordinal)
        {
            ["ancestry"] = new("Core", "Your people. Sets hit points, size, speed and which heritages and ancestry feats are open to you."),
            ["heritage"] = new("Core", "A twist on your ancestry, chosen at 1st level, such as a hardier bloodline or a parent from another people."),
            ["background"] = new("Core", "What you did before adventuring. Gives two attribute boosts, a trained skill, a Lore and a skill feat."),
            ["class"] = new("Core", "Your adventuring job. The biggest single choice: it sets your hit points, proficiencies and most of your features."),
            ["class-feature"] = new("Core", "The abilities a class hands you automatically at set levels, no feat slot needed."),
            ["apparition"] = new("Class options", "An animist's apparitions, the spirits they bond with; each one adds spells and skills, and you attune to some each day."),
            ["arcane-school"] = new("Class options", "A wizard's arcane school, chosen at 1st level, which shapes the extra spells they learn."),
            ["arcane-thesis"] = new("Class options", "A wizard's thesis, picked at 1st level: a special trick with spells or their familiar that sets their style of study."),
            ["bloodline"] = new("Class options", "A sorcerer's bloodline, chosen at 1st level. It sets their magic tradition, bonus spells and granted skills."),
            ["cause"] = new("Class options", "A champion's cause, chosen at 1st level, which sets their code of conduct and the reaction they use to protect allies."),
            ["conscious-mind"] = new("Class options", "A psychic's conscious mind, chosen at 1st level, which decides their signature psi cantrips and extra spells."),
            ["doctrine"] = new("Class options", "A cleric's doctrine, chosen at 1st level: lean into spellcasting or into armour and weapons."),
            ["druidic-order"] = new("Class options", "A druid's order, chosen at 1st level, which grants an extra focus spell, a skill and access to related feats."),
            ["eidolon"] = new("Class options", "A summoner's eidolon, chosen at 1st level: the bonded partner creature whose type sets its stats and your magic."),
            ["element"] = new("Class options", "A kineticist's elemental gate, picked at 1st level. The element decides which impulses you can reach for."),
            ["epithet"] = new("Class options", "An exemplar's epithets, titles they earn as they level that add a new benefit to how they fight."),
            ["fatal-method"] = new("Class options", "A necromancer's fatal method, a 1st-level choice that sets how they work alongside their undead."),
            ["grim-fascination"] = new("Class options", "A necromancer's grim fascination, chosen at 1st level, which picks a focus like blood or bone and grants a spell."),
            ["hunters-edge"] = new("Class options", "A ranger's hunter's edge, chosen at 1st level. It adds a bonus against whatever target you've marked as your prey."),
            ["hybrid-study"] = new("Class options", "A magus's hybrid study, chosen at 1st level, which blends a fighting style with their spell-infused strikes."),
            ["ikon"] = new("Class options", "An exemplar's ikons, the few treasured items that hold their divine spark and grant powers you can shift between."),
            ["implement"] = new("Class options", "A thaumaturge's implements, the objects they hold to channel their tricks. You pick your first at 1st level."),
            ["innovation"] = new("Class options", "An inventor's innovation, chosen at 1st level: the armour, weapon or construct they keep upgrading."),
            ["instinct"] = new("Class options", "A barbarian's instinct, chosen at 1st level, which shapes what fuels their rage and what extra damage it deals."),
            ["lesson"] = new("Class options", "A witch's lessons, extra hexes and spells learned from their patron through feats."),
            ["methodology"] = new("Class options", "An investigator's methodology, chosen at 1st level, which sets how they crack cases and adds skills to match."),
            ["muse"] = new("Class options", "A bard's muse, chosen at 1st level, which grants a feat and an extra spell and leans the bard toward a play style."),
            ["mystery"] = new("Class options", "An oracle's mystery, chosen at 1st level. It grants spells and skills, along with the curse that comes with them."),
            ["patron"] = new("Class options", "A witch's patron, chosen at 1st level, which sets their magic tradition, a hex cantrip and their familiar's gift."),
            ["practice"] = new("Class options", "An animist's practice, a 1st-level choice of how they relate to spirits, which grows as they level."),
            ["racket"] = new("Class options", "A rogue's racket, chosen at 1st level, which sets their specialty and bends how their sneak attacks work."),
            ["research-field"] = new("Class options", "An alchemist's research field, chosen at 1st level: bombs, healing, mutagens or poisons, with extra free items."),
            ["style"] = new("Class options", "A swashbuckler's style, chosen at 1st level, which names the skill actions that give them panache."),
            ["subconscious-mind"] = new("Class options", "A psychic's subconscious mind, chosen at 1st level, which sets their key attribute and how they unleash their power."),
            ["way"] = new("Class options", "A gunslinger's way, chosen at 1st level, which sets their fighting style and their special reload and initial deeds."),

            ["feat"] = new("Feats", "Every feat: ancestry, class, skill and general. Filter by level and trait to see what your next slot can take."),
            ["archetype"] = new("Archetypes", "Side paths that trade class feats for another theme or a second class. Start one with its dedication feat."),

            ["spell"] = new("Spells and rituals", "Every spell, cantrip and focus spell. Check the traditions to see who can cast it and the rank to see when."),
            ["ritual"] = new("Spells and rituals", "Long, costly group castings anyone can attempt with the right skills, for effects too big for a normal spell."),
            ["tradition"] = new("Traditions", "The four kinds of magic: arcane, divine, occult and primal. Your class tells you which list you cast from."),

            ["equipment"] = new("Equipment", "Adventuring gear, worn items, consumables and magic items. The place to shop between sessions."),
            ["weapon"] = new("Equipment", "Every weapon with its damage, hands and traits. Compare traits to find one that suits how you fight."),
            ["armor"] = new("Equipment", "Armour by category, with its AC bonus, Dex cap and penalties, so you can match it to your proficiency."),
            ["shield"] = new("Equipment", "Shields with their hardness and hit points. Raise one for AC, or block damage with the right reaction."),
            ["item-bonus"] = new("Equipment", "Items that give an item bonus and how big it is, handy when you want a +1 or +2 to a particular check."),
            ["class-kit"] = new("Equipment", "Ready-made starting gear for each class, a quick way to skip shopping at 1st level."),
            ["relic"] = new("Relics and curses", "Gifts a relic can unlock, the powers it gains as it grows alongside its owner through a campaign."),
            ["set-relic"] = new("Relics and curses", "Relics that come as a matched set, which grow stronger when you gather and wear more of the pieces."),
            ["curse"] = new("Relics and curses", "Curses that ride along on a magic item, the catch you only discover once you're using it."),

            ["action"] = new("Actions and conditions", "Basic and specialty actions you spend on your turn. Look here when you want to know what an action costs."),
            ["condition"] = new("Actions and conditions", "States like frightened, off-guard or dying, with how they change your rolls and when they end."),
            ["skill"] = new("Skills", "The sixteen skills plus Lore, with what each one lets you do in and out of combat."),
            ["skill-general-action"] = new("Skills", "Activities that work with more than one skill, like earning income, identifying magic or recalling knowledge."),

            ["trait"] = new("Rules terms", "The keywords stamped on rules. A trait tells you how something interacts with other rules, so open one when unsure."),
            ["armor-group"] = new("Rules terms", "Families of armour. The group decides what armour specialization gives you when you reach it."),
            ["weapon-group"] = new("Rules terms", "Families of weapons. The group decides the critical specialization effect and which feats apply."),
            ["deity"] = new("Gods and faith", "Gods and philosophies, with their edicts, favoured weapon, domains and the spells they grant clerics."),
            ["deity-category"] = new("Gods and faith", "Ways the gods are grouped, handy for browsing faiths by region or kind."),
            ["domain"] = new("Gods and faith", "The areas a god holds sway over. Clerics and champions draw domain focus spells from their god's list."),
            ["animal-companion"] = new("Companions and allies", "Base animal companions for rangers, druids and others, with each creature's size, attacks and support benefit."),
            ["animal-companion-advanced"] = new("Companions and allies", "Advanced options that improve a mature animal companion in a particular direction."),
            ["animal-companion-specialization"] = new("Companions and allies", "Late upgrades for a nimble or savage companion that give it a specialty such as ambushing or tracking."),
            ["animal-companion-unique"] = new("Companions and allies", "One-of-a-kind animal companions with their own stat blocks, usually tied to a specific adventure."),
            ["familiar-ability"] = new("Companions and allies", "The abilities you pick for your familiar each day, for the familiar itself or for you as its master."),
            ["familiar-specific"] = new("Companions and allies", "Named familiar types with a fixed bundle of abilities, instead of picking abilities one by one."),
            ["follower"] = new("Companions and allies", "Allies who travel with the party under your direction, each with its own statistics and a role like scout or medic."),
            ["language"] = new("Other", "Languages you can speak and read. Your ancestry grants some, and a high Intelligence adds more."),
            ["source"] = new("Other", "The books and adventures the rules come from, so you can see where an option was printed."),
            ["deviant-ability-classification"] = new("Other", "Families of deviant feats, the odd inborn powers some characters awaken, grouped by shared theme."),
            ["draconic-exemplar"] = new("Other", "The kinds of dragon a draconic choice can point to, setting things like damage type for bloodlines and heritages."),
            ["hellknight-order"] = new("Other", "The orders of the Hellknight archetype, each with its own focus that shapes the feats and duties of its members."),
            ["mythic-calling"] = new("Other", "In mythic games, the calling that sets which mythic skills and feats your character leans on."),
            ["runesmith-rune"] = new("Other", "The runes a runesmith traces and invokes on allies, foes and gear, each with a lasting and an invoked effect."),
            ["tactic"] = new("Other", "A commander's tactics, the orders they prepare and give to let allies move or strike on the commander's turn."),
        };

    private static readonly IReadOnlyDictionary<GroupKey, IReadOnlyList<string>> Sections = new Dictionary<GroupKey, IReadOnlyList<string>>
    {
        [GroupKey.Build] = ["Core", "Class options"],
        [GroupKey.Feats] = ["Feats", "Archetypes"],
        [GroupKey.Spells] = ["Spells and rituals", "Traditions"],
        [GroupKey.Gear] = ["Equipment", "Relics and curses"],
        [GroupKey.Play] = ["Actions and conditions", "Skills"],
        [GroupKey.Reference] = ["Rules terms", "Gods and faith", "Companions and allies", "Other"],
    };

    public static CategoryNote? Of(string category) => All.GetValueOrDefault(category);

    public static IReadOnlyList<string> SectionOrder(GroupKey group) => Sections.GetValueOrDefault(group, []);
}

/// <summary>Keyed by the trait's name exactly as the seed spells it. A trait with no entry still
/// opens; it shows its facts and where it is used, just no gloss.</summary>
public static class TraitGlossary
{
    public static IReadOnlyDictionary<string, string> All { get; } =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["Manipulate"] = "You have to move your hands to do this, so it can trigger reactions like Reactive Strike.",
            ["Concentrate"] = "Takes mental focus. You can't do it while too distracted, and some reactions punish it.",
            ["Move"] = "You change position doing this, so it can trigger reactions from enemies you move near or past.",
            ["Attack"] = "Counts toward your multiple attack penalty: each attack after the first in a turn is harder to land.",
            ["Flourish"] = "A showy move. You can use only one action with this trait per turn.",
            ["Press"] = "A follow-up move. You can only use it if you've already attacked this turn, so it always takes a penalty.",
            ["Open"] = "An opener. You can only use it if you haven't used an attack action yet this turn.",
            ["Stance"] = "A fighting posture you enter. It lasts until you leave it or fight ends, and you can hold only one at a time.",
            ["Fortune"] = "Lets you roll twice and keep the better. Only one fortune effect applies to a roll.",
            ["Misfortune"] = "Makes you roll twice and keep the worse. If fortune and misfortune both apply, they cancel out.",
            ["Incapacitation"] = "Knocks a target out of the fight, so creatures of much higher level than the effect get a better outcome.",
            ["Cantrip"] = "A spell you can cast at will without using a spell slot. It scales to half your level, rounded up.",
            ["Focus"] = "A special spell from your class or deity, cast with Focus Points instead of slots. Refocus to regain points.",
            ["Spellshape"] = "An action you take just before casting a spell to change how that spell works.",
            ["Metamagic"] = "The pre-Remaster name for spellshape: an action you take right before a spell to alter it.",
            ["Exploration"] = "Something you do while travelling or searching between fights, over minutes rather than rounds.",
            ["Downtime"] = "An activity that takes days of free time, like crafting, training or earning money.",
            ["Secret"] = "The GM rolls this for you in secret, so you don't know for sure how well you did.",
            ["Mental"] = "Works on the mind, so mindless creatures are immune. Mental damage is harmful only to thinking creatures.",
            ["Emotion"] = "Plays on feelings. Creatures without emotions are unaffected, and some abilities guard against it.",
            ["Fear"] = "Frightens its target. Anything that protects against fear, or is immune to it, blunts this.",
            ["Linguistic"] = "Depends on words. A creature that doesn't understand your language is unaffected.",
            ["Auditory"] = "Depends on sound, so a target that can't hear it is unaffected.",
            ["Visual"] = "Depends on sight, so a target that can't see it is unaffected.",
            ["Olfactory"] = "Depends on smell, so a target that can't smell it is unaffected.",
            ["Healing"] = "Restores hit points or cures harm. Some effects and creatures react specially to healing.",
            ["Light"] = "Makes light. It can counteract magical darkness, and darkness can counteract it.",
            ["Darkness"] = "Makes or deepens darkness. It can counteract magical light, and light can counteract it.",
            ["Death"] = "Can kill outright. If it drops you to 0 hit points, you die at once instead of falling unconscious.",
            ["Detection"] = "Helps you notice or locate something, often something hidden or magical.",
            ["Scrying"] = "Lets you watch somewhere from afar. Targets may get a save, and some magic blocks it.",
            ["Prediction"] = "Reveals something about what is going to happen.",
            ["Teleportation"] = "Moves a creature or object instantly without crossing the space between, so it doesn't trigger movement reactions.",
            ["Polymorph"] = "Changes a creature into a new shape. Only one polymorph applies at once; a new one replaces the last.",
            ["Morph"] = "Alters part of a creature's body, like growing claws, without a full shapechange.",
            ["Extradimensional"] = "Creates or uses a pocket of space outside the normal world, like a bag of holding.",
            ["Aura"] = "Covers an area around a creature or object and moves with it.",
            ["Minion"] = "A creature that acts only when you spend an action to command it, usually getting two actions.",
            ["Summoned"] = "A creature brought in by a spell, which vanishes when the spell ends and can't summon others.",
            ["Subtle"] = "Casting this spell has no obvious signs, so onlookers won't notice you did it.",
            ["Sleep"] = "Puts creatures to sleep. Creatures that never sleep are unaffected.",
            ["Splash"] = "Hits the target and also spatters a little damage on everything next to it, even on a miss.",
            ["Holy"] = "Tied to sacred power. Unholy creatures are often weak to it.",
            ["Unholy"] = "Tied to profane power. Holy creatures are often weak to it.",
            ["Sanctified"] = "If your deity is holy or unholy, you can give this effect that trait too.",
            ["Consecration"] = "Blesses an area for a long time, making it sacred ground.",
            ["Virulent"] = "A stubborn affliction: it takes two successful saves in a row to make it ease off.",

            ["Poison"] = "Deals poison damage or inflicts a toxin. Poison-immune creatures ignore it.",
            ["Disease"] = "A sickness that progresses in stages over days until you shake it off.",
            ["Curse"] = "A magical affliction that often lingers until removed by specific magic.",
            ["Contact"] = "A poison that works when it touches skin, usually taking a minute to set in.",
            ["Ingested"] = "A poison that has to be eaten or drunk to take effect.",
            ["Inhaled"] = "A poison that has to be breathed in, usually as a cloud; holding your breath helps.",
            ["Injury"] = "A poison applied to a weapon, which takes effect when you hit and deal piercing or slashing damage.",

            ["Fire"] = "Uses or deals fire. Creatures with fire resistance or weakness respond to it.",
            ["Cold"] = "Uses or deals cold. Creatures with cold resistance or weakness respond to it.",
            ["Electricity"] = "Uses or deals electricity. Creatures with electricity resistance or weakness respond to it.",
            ["Acid"] = "Uses or deals acid. Creatures with acid resistance or weakness respond to it.",
            ["Sonic"] = "Uses or deals sound-based damage. Creatures with sonic resistance or weakness respond to it.",
            ["Force"] = "Uses or deals force, pure magical energy that few creatures resist.",
            ["Spirit"] = "On an effect, harms a creature's spirit; on a creature, it's a being made of spirit, like a ghost.",
            ["Vitality"] = "Life energy. It heals the living and harms the undead.",
            ["Void"] = "Death energy. It harms the living and heals the undead.",
            ["Positive"] = "Pre-Remaster name for vitality energy, which heals the living and harms the undead.",
            ["Negative"] = "Pre-Remaster name for void energy, which harms the living and heals the undead.",
            ["Air"] = "Of the element air. Elemental effects interact with creatures and abilities tied to that element.",
            ["Earth"] = "Of the element earth. Elemental effects interact with creatures and abilities tied to that element.",
            ["Water"] = "Of the element water. Elemental effects interact with creatures and abilities tied to that element.",
            ["Wood"] = "Of the element wood. Elemental effects interact with creatures and abilities tied to that element.",
            ["Metal"] = "Of the element metal. Elemental effects interact with creatures and abilities tied to that element.",
            ["Plant"] = "On an effect, it involves plants; on a creature, it's a living plant.",

            ["Arcane"] = "Arcane magic, learned through study. Wizards and magi cast from this list.",
            ["Divine"] = "Divine magic, granted by faith. Clerics and champions draw on this list.",
            ["Occult"] = "Occult magic, drawn from the mind and hidden mysteries. Bards and psychics cast from this list.",
            ["Primal"] = "Primal magic, drawn from nature. Druids and many rangers cast from this list.",
            ["Abjuration"] = "A pre-Remaster spell school for protective magic. Older content still carries it; it no longer affects rules.",
            ["Conjuration"] = "A pre-Remaster spell school for summoning and creating things. Older content still carries it.",
            ["Divination"] = "A pre-Remaster spell school for gaining knowledge. Older content still carries it.",
            ["Enchantment"] = "A pre-Remaster spell school for affecting minds. Older content still carries it.",
            ["Evocation"] = "A pre-Remaster spell school for raw energy like blasts of fire. Older content still carries it.",
            ["Illusion"] = "Creates false sights or sounds. Also a pre-Remaster spell school that older content still carries.",
            ["Necromancy"] = "A pre-Remaster spell school for life and death energy. Older content still carries it.",
            ["Transmutation"] = "A pre-Remaster spell school for changing bodies and matter. Older content still carries it.",

            ["Uncommon"] = "Not available by default. You need a feat, background, GM okay or story reason to take it.",
            ["Rare"] = "Very hard to find. You usually get it only through the story or with the GM's permission.",
            ["Unique"] = "One of a kind in the world, like a named artifact or a specific person.",

            ["General"] = "A general feat, open to any character. You get a general feat slot every few levels.",
            ["Skill"] = "A skill feat, gated by your proficiency in a skill. You can take it in a skill or general feat slot.",
            ["Archetype"] = "An archetype feat, taken in a class feat slot once you have the archetype's dedication feat.",
            ["Dedication"] = "Starts an archetype. You need to take two more of its feats before starting another dedication.",
            ["Multiclass"] = "An archetype that grants the basics of another class, like its spells or core feature.",
            ["Lineage"] = "A feat tied to your family line. You can have only one lineage feat, usually taken at 1st level.",
            ["Mythic"] = "Part of the optional mythic rules, used in campaigns where the heroes gain legendary power.",
            ["Deviant"] = "A deviant feat, a strange inborn power that awakens in a character.",
            ["Aftermath"] = "A feat you gain after living through a particular event or exposure, usually with the GM's agreement.",

            ["Alchemist"] = "Belongs to the alchemist class. Feats with it need that class or its archetype.",
            ["Animist"] = "Belongs to the animist class. Feats with it need that class or its archetype.",
            ["Barbarian"] = "Belongs to the barbarian class. Feats with it need that class or its archetype.",
            ["Bard"] = "Belongs to the bard class. Feats with it need that class or its archetype.",
            ["Champion"] = "Belongs to the champion class. Feats with it need that class or its archetype.",
            ["Cleric"] = "Belongs to the cleric class. Feats with it need that class or its archetype.",
            ["Commander"] = "Belongs to the commander class. Feats with it need that class or its archetype.",
            ["Druid"] = "Belongs to the druid class. Feats with it need that class or its archetype.",
            ["Exemplar"] = "Belongs to the exemplar class. Feats with it need that class or its archetype.",
            ["Fighter"] = "Belongs to the fighter class. Feats with it need that class or its archetype.",
            ["Guardian"] = "Belongs to the guardian class. Feats with it need that class or its archetype.",
            ["Gunslinger"] = "Belongs to the gunslinger class. Feats with it need that class or its archetype.",
            ["Inventor"] = "Belongs to the inventor class. Feats with it need that class or its archetype.",
            ["Investigator"] = "Belongs to the investigator class. Feats with it need that class or its archetype.",
            ["Kineticist"] = "Belongs to the kineticist class. Feats with it need that class or its archetype.",
            ["Magus"] = "Belongs to the magus class. Feats with it need that class or its archetype.",
            ["Monk"] = "Belongs to the monk class. On a weapon, monks can use it with abilities that normally need unarmed attacks.",
            ["Necromancer"] = "Belongs to the necromancer class. Feats with it need that class or its archetype.",
            ["Oracle"] = "Belongs to the oracle class. Feats with it need that class or its archetype.",
            ["Psychic"] = "Belongs to the psychic class. Feats with it need that class or its archetype.",
            ["Ranger"] = "Belongs to the ranger class. Feats with it need that class or its archetype.",
            ["Rogue"] = "Belongs to the rogue class. Feats with it need that class or its archetype.",
            ["Runesmith"] = "Belongs to the runesmith class. Feats with it need that class or its archetype.",
            ["Sorcerer"] = "Belongs to the sorcerer class. Feats with it need that class or its archetype.",
            ["Summoner"] = "Belongs to the summoner class. Feats with it need that class or its archetype.",
            ["Swashbuckler"] = "Belongs to the swashbuckler class. Feats with it need that class or its archetype.",
            ["Thaumaturge"] = "Belongs to the thaumaturge class. Feats with it need that class or its archetype.",
            ["Witch"] = "Belongs to the witch class. Feats with it need that class or its archetype.",
            ["Wizard"] = "Belongs to the wizard class. Feats with it need that class or its archetype.",

            ["Impulse"] = "A kineticist's elemental action. Using it needs your kinetic aura to be active.",
            ["Overflow"] = "A big kineticist impulse that spends your kinetic aura, so you'll need to channel again afterwards.",
            ["Composition"] = "A bard's performance spell. You can cast only one composition per turn.",
            ["Hex"] = "A witch's patron spell. You can cast only one hex per turn.",
            ["Rage"] = "Only usable while you're raging, and it ends when your rage does.",
            ["Eidolon"] = "Tied to a summoner's eidolon, the bonded creature that shares their hit points.",
            ["Evolution"] = "A summoner feat that changes or improves their eidolon.",
            ["Cursebound"] = "An oracle action that draws on their curse, making it worse each time.",
            ["Additive"] = "An alchemist feat you add to a bomb or elixir as you make it. Only one additive per item.",
            ["Tactic"] = "A commander's prepared order that lets allies act on the commander's cue.",
            ["Rune"] = "A runesmith rune, traced onto something and later invoked for a burst of effect.",
            ["Apparition"] = "Tied to an animist's apparitions, the spirits they attune to each day.",
            ["Ikon"] = "An exemplar's ikon, a treasured item or body part that holds a spark of divine power.",

            ["Human"] = "Belongs to the human ancestry. Ancestry feats with it are for humans.",
            ["Dwarf"] = "Belongs to the dwarf ancestry. On a weapon, it ties in to dwarven weapon familiarity feats.",
            ["Elf"] = "Belongs to the elf ancestry. On a weapon, it ties in to elven weapon familiarity feats.",
            ["Gnome"] = "Belongs to the gnome ancestry. On a weapon, it ties in to gnome weapon familiarity feats.",
            ["Goblin"] = "Belongs to the goblin ancestry. On a weapon, it ties in to goblin weapon familiarity feats.",
            ["Halfling"] = "Belongs to the halfling ancestry. On a weapon, it ties in to halfling weapon familiarity feats.",
            ["Orc"] = "Belongs to the orc ancestry. On a weapon, it ties in to orc weapon familiarity feats.",
            ["Kobold"] = "Belongs to the kobold ancestry. Ancestry feats with it are for kobolds.",
            ["Leshy"] = "Belongs to the leshy ancestry, plant spirits in living bodies. Ancestry feats with it are for leshies.",
            ["Nephilim"] = "A versatile heritage for someone with a celestial or fiendish ancestor. Feats with it need that heritage.",
            ["Catfolk"] = "Belongs to the catfolk ancestry. Ancestry feats with it are for catfolk.",
            ["Tengu"] = "Belongs to the tengu ancestry. Ancestry feats with it are for tengus.",
            ["Lizardfolk"] = "Belongs to the lizardfolk ancestry. Ancestry feats with it are for lizardfolk.",
            ["Hobgoblin"] = "Belongs to the hobgoblin ancestry. Ancestry feats with it are for hobgoblins.",
            ["Ratfolk"] = "Belongs to the ratfolk ancestry. Ancestry feats with it are for ratfolk.",
            ["Automaton"] = "Belongs to the automaton ancestry. Ancestry feats with it are for automatons.",
            ["Dragonblood"] = "A versatile heritage for someone with a dragon in their family line. Feats with it need that heritage.",
            ["Humanoid"] = "A creature type: people shaped roughly like humans, including most ancestries.",
            ["Animal"] = "A creature type: ordinary beasts without human-level intelligence.",
            ["Beast"] = "A creature type: animal-like creatures with magic or a mind beyond a normal animal's.",
            ["Undead"] = "A creature type: once-living things animated by void energy. Vitality harms them and void heals them.",

            ["Magical"] = "Carries magic, so it can be detected and dispelled, and it can bypass some resistances.",
            ["Invested"] = "You must invest it each day to get its magic. You can have at most 10 invested items at once.",
            ["Consumable"] = "Used up when you use it. Most are one use and then gone.",
            ["Alchemical"] = "Made by alchemy, not magic, so it can't be dispelled or spotted by magic that finds spells.",
            ["Elixir"] = "An alchemical liquid you drink to gain its effect.",
            ["Mutagen"] = "An elixir that changes your body, giving a benefit and a drawback for a while.",
            ["Bomb"] = "An alchemical explosive you throw as a ranged attack. Most also splash nearby creatures.",
            ["Potion"] = "A magic liquid you drink to gain its effect.",
            ["Oil"] = "A magic liquid you rub onto an item or creature to apply its effect.",
            ["Scroll"] = "Holds one spell. If the spell is on your list, you can cast it from the scroll once.",
            ["Talisman"] = "A one-use charm fixed to armour, a shield or a weapon, which you trigger when its condition comes up.",
            ["Wand"] = "Holds a spell you can cast once a day, with a risky option to push it for a second use.",
            ["Staff"] = "Gains charges each day when you prepare it, which you spend to cast the spells it holds.",
            ["Snare"] = "A quick trap made in advance and set in a square, triggered when a creature enters it.",
            ["Trap"] = "A device or hazard built to catch or harm whoever sets it off.",
            ["Drug"] = "Gives a short boost with side effects, and taking it repeatedly risks addiction.",
            ["Artifact"] = "An item of legendary power that can't be crafted and is very hard to destroy.",
            ["Cursed"] = "Carries a curse that usually reveals itself only once you use the item, and is hard to be rid of.",
            ["Intelligent"] = "An item with its own mind and personality, which may help or argue with its wielder.",
            ["Precious"] = "Made from a special material, like cold iron or silver, that affects certain creatures or has other perks.",
            ["Structure"] = "Unfolds into a building or other large structure, so it needs open space to use.",
            ["Companion"] = "An item made for an animal companion or similar creature to wear.",
            ["Tattoo"] = "A magic tattoo on your skin, so it needs no hands to carry.",
            ["Spellheart"] = "An item you set into armour or a weapon, like a talisman, but it stays and grants lasting magic.",
            ["Apex"] = "Raises one of your attributes when invested. Only one apex item works for you at a time.",
            ["Grimoire"] = "A magic spellbook that helps a caster who prepares spells from it.",
            ["Catalyst"] = "A consumable you add while casting a specific spell to boost what it does.",
            ["Gadget"] = "A one-use mechanical device, not magical, that anyone trained can build and use.",
            ["Mechanical"] = "Works by gears and machinery rather than magic.",
            ["Clockwork"] = "Driven by wound-up clockwork. It typically needs winding to keep running.",
            ["Graft"] = "A living part implanted into your body to give you an ability.",
            ["Fulu"] = "A paper charm you attach to a creature or object; it's used up when its magic triggers.",
            ["Relic"] = "An item that grows in power along with its owner over a campaign.",
            ["Adjustment"] = "A modification you add to armour, a weapon or other gear to change how it works.",
            ["Coda"] = "An instrument that also works as a staff, holding spells a performer casts through it.",
            ["Focused"] = "Gives you an extra Focus Point once per day, usable only for focus spells.",

            ["Agile"] = "Your multiple attack penalty is smaller with this weapon, so follow-up attacks land more often.",
            ["Finesse"] = "You can use Dexterity instead of Strength on attack rolls with this melee weapon.",
            ["Deadly"] = "On a critical hit, adds an extra damage die of the listed size.",
            ["Fatal"] = "On a critical hit, the damage die grows to the listed size and you add one more die.",
            ["Forceful"] = "Deals extra damage on the second and later hits in a turn.",
            ["Sweep"] = "Gives a bonus when you attack a different target than your last attack this turn.",
            ["Reach"] = "Lets you attack creatures farther away than normal, usually 10 feet.",
            ["Thrown"] = "You can throw this weapon as a ranged attack, adding Strength to its damage.",
            ["Trip"] = "Lets you Trip with this weapon, adding its item bonus to the check.",
            ["Ranged Trip"] = "Lets you Trip a creature at range with this weapon.",
            ["Shove"] = "Lets you Shove with this weapon, adding its item bonus to the check.",
            ["Disarm"] = "Lets you Disarm with this weapon, adding its item bonus to the check.",
            ["Grapple"] = "Lets you Grapple with this weapon, adding its item bonus to the check.",
            ["Versatile"] = "You can deal the listed alternate damage type instead of its normal one.",
            ["Two-Hand"] = "Wielded in two hands, it uses the listed bigger damage die.",
            ["Free-Hand"] = "Leaves that hand free enough to hold or use other things while you wield it.",
            ["Volley"] = "Hard to aim up close. You take a penalty against targets within the listed range.",
            ["Propulsive"] = "Adds half your Strength to damage if it's positive, or all of it if it's negative.",
            ["Backstabber"] = "Deals extra precision damage to targets that are off-guard.",
            ["Backswing"] = "After you miss with it, you get a bonus on your next attack with it this turn.",
            ["Parry"] = "You can spend an action to raise it defensively for a bonus to AC.",
            ["Nonlethal"] = "Its damage knocks creatures out instead of killing them.",
            ["Concussive"] = "Deals piercing or bludgeoning, whichever the target resists less.",
            ["Kickback"] = "Hits hard but kicks back, giving a penalty unless you're strong enough or brace it.",
            ["Scatter"] = "Its shot spreads, splashing damage on creatures near your target.",
            ["Repeating"] = "Fed by a magazine, so you can fire several times before a full reload.",
            ["Capacity"] = "Holds several loaded shots; you rotate to the next with an action instead of reloading.",
            ["Combination"] = "A firearm and a melee weapon built into one, so you can shoot or strike with the same item.",
            ["Bulwark"] = "Heavy armour that protects you from damaging Reflex effects, replacing your Dexterity there.",
            ["Flexible"] = "Armour loose enough that its check penalty doesn't apply to some athletic or acrobatic moves.",
            ["Noisy"] = "Armour that makes noise, giving a penalty to Stealth.",
            ["Comfort"] = "Armour comfortable enough to sleep in without waking up tired.",
        };

    public static string? Of(string trait) => All.GetValueOrDefault(trait);
}
