import { writeFileSync } from 'node:fs';
import StyleDictionary from 'style-dictionary';
import { createPropertyFormatter, sortByName } from 'style-dictionary/utils';

const PRIMITIVES = 'tokens/primitive/*.json';
const OUT = 'dist/tokens.css';

StyleDictionary.registerTransform({
  name: 'cubicBezier/css',
  type: 'value',
  filter: (token) => token.$type === 'cubicBezier',
  transform: (token) => `cubic-bezier(${token.$value.join(', ')})`,
});

// Emits declarations only. build() assembles them into selectors itself, because one
// theme's values have to appear under three different selectors and Style Dictionary's
// css/variables format writes its own.
StyleDictionary.registerFormat({
  name: 'css/declarations',
  format: ({ dictionary, options }) => {
    const declaration = createPropertyFormatter({
      dictionary,
      format: 'css',
      usesDtcg: options?.usesDtcg ?? true,
    });
    return dictionary.allTokens.sort(sortByName).map(declaration).join('\n');
  },
});

const isSemantic = (token) => !token.filePath.includes('primitive');

async function declarations(sources, filter) {
  const sd = new StyleDictionary({
    source: sources,
    log: { verbosity: 'silent' },
    platforms: {
      css: {
        // Explicit rather than transformGroup 'css': size/rem would rewrite the tap-target
        // pixel floors and mangle the one percentage value. These values are already valid CSS.
        transforms: ['attribute/cti', 'name/kebab', 'cubicBezier/css'],
        files: [{ destination: 'decls.css', format: 'css/declarations', filter }],
      },
    },
  });
  const [file] = await sd.formatPlatform('css');
  return file.output.trimEnd();
}

const indent = (block, pad) =>
  block.split('\n').map((line) => (line.trim() ? pad + line.trim() : '')).join('\n');

const base = await declarations([PRIMITIVES, 'tokens/semantic/light.json']);
const dark = await declarations([PRIMITIVES, 'tokens/semantic/dark.json'], isSemantic);

const css = `/* Generated by tools/tokens. Do not edit by hand; edit tokens/ and run npm run build.
   Checked in so a machine with only the .NET SDK can build and run the app. */

:root {
  color-scheme: light dark;

${indent(base, '  ')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${indent(dark, '    ')}
  }
}

:root[data-theme="dark"] {
${indent(dark, '  ')}
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --motion-duration-quick: 0ms;
    --motion-duration-sheet: 0ms;
  }
}
`;

writeFileSync(OUT, css);
const count = (css.match(/^\s+--/gm) ?? []).length;
console.log(`wrote ${OUT}: ${count} declarations, ${css.length} bytes`);
